### ISSUE TITLE
 Ignore URL feature

### ISSUE THREAD

**Issue by Jasper-Mui** [lixiaoqity/testLink#10]
I would like to add this feature to your project.

**Comment by lixiaoqity** [comment]
Wonderful. Expect your contribution.

**Comment by Jasper-Mui** [comment]
Hey @lixiaoqity I have finished the feature please see it here https://github.com/Jasper-Mui/testLink. The branch is name issue-10.

**Comment by lixiaoqity** [comment]
When I test it using the command "testLinks -i testIgnoreTestFile.txt test1.html". The output is as follow.
"This is invalid.  It doesn't use http:// or https://
www.badlink".
It seems that I can't continue to test the test1.html file. I don't know if my operation is right. Please help me to check it. Thanks.

**Comment by Jasper-Mui** [comment]
Hi sorry it seems I forgot to press comment on my last message. Please edit the testIgnoreTestFile.txt. It seems I left the testIgnoreTestFile.txt in the error state when I was testing. 

Please edit the txt file to try the following.

This will run fine basically an empty file.
\# 1. Empty file, nothing will be ignored

This would ignore any links starting with "https://github.com"
https://github.com

Same thing as above as # comment will not be picked up
\# this is a comment 
https://www.google.com

And as the file is right now it is the error one where invalid syntax for the ignore file was used.

**Comment by lixiaoqity** [comment]
I test it successfully. Wonderful job. Thanks for your contribution.
