### ISSUE TITLE
Name in package.json must be lowercase

### ISSUE THREAD

**Issue by tianlangwu** [lixiaoqity/testLink#3]
Your name in the package.json contains Uppercase character. The documentation said that all the "The "name" field contains your package’s name, and must be lowercase and one word, and may contain hyphens and underscores."

**Comment by lixiaoqity** [comment]
> Your name in the package.json contains Uppercase character. The documentation said that all the "The "name" field contains your package’s name, and must be lowercase and one word, and may contain hyphens and underscores."

Thank your for reminder. I have fixed it.
